# HOST = "localhost"
# USERNAME = "root"
# PASSWORD = "triplec"
# DBNAME = "aggiehack"

HOST = "localhost"
USERNAME = "testuser"
PASSWORD = "test606"
DBNAME = "aggiehack"

MAX_DISTANCE = 2 #km
WALKING_TYPE = "walking"
BUS_TYPE = "bus"
BUS_VELOCITY = 35 # average bus velocity km/hr
WALKING_VELOCITY = 5
START_NODE_ID = -1

LATITUDE_UPPER_BOUND = 30.746475
LATITUDE_LOWER_BOUND = 30.559814
LONGTITUDE_LEFT_BOUND = -96.463036
LONGTITUDE_RIGHT_BOUND = -96.276269
