MAX_DISTANCE = 2 #km
WALKING_TYPE = "walking"
BUS_TYPE = "bus"
BUS_VELOCITY = 45 # average bus velocity km/hr
WALKING_VELOCITY = 5
START_NODE_ID = -1

LATITUDE_UPPER_BOUND = 30.746475
LATITUDE_LOWER_BOUND = 30.559814
LONGTITUDE_LEFT_BOUND = -96.463036
LONGTITUDE_RIGHT_BOUND = -96.276269

K_SHORTEST = 5
PICKLE_FILE_BUS = "pickle_files/bus.pkl"
PICKLE_FILE_WALK = "pickle_files/walk.pkl"
PICKLE_FILE_LOCATION = "pickle_files/location.pkl"