csg_data:
    resource: "@CsgDataBundle/Resources/config/routing.xml"
    prefix:   /data

csg_route_finder:
    resource: "@CsgRouteFinderBundle/Resources/config/routing.xml"
    prefix:   /

#csg_demo:
#    resource: "@CsgDemoBundle/Resources/config/routing.xml"
#    prefix:   /demo

