_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Command/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Command/DemoController.php"
    type:     annotation
    prefix:   /demo